name: Action for Testing the action itself
on: [push,workflow_dispatch] 
jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:  
      - name: checkout
        uses: actions/checkout@v4
      - name: Pull Docker Image
        run: docker pull gcr.io/google-appengine/python
      - name: "Run Tests"
        uses: ./
        with: 
         dockerimage: gcr.io/google-appengine/python
         args: --config tests/python_command_tests.yaml --config tests/python_file_tests.yaml
      - name: "Run Tests and Generate JSON reports"
        uses: ./
        with: 
         dockerimage: gcr.io/google-appengine/python
         args: --config tests/python_command_tests.yaml --config tests/python_file_tests.yaml --output junit --test-report junitreport.xml
      - name: Upload Junit Report xml
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Junitreport
          path: junitreport.xml